Attendance/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home.urls')),
    path('student/', include('students.urls')),
    path('teacher/', include('teachers.urls')),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.start, name='start'),
    path('registration', views.registration, name='registration'),
]

students/urls.py
from django.urls import path
from . import views


app_name = 'student'
urlpatterns = [
    path('login/', views.login, name='loginStudent'),
    path('register/', views.register, name='registerStudent'),
]

teachers/urls.py
from django.urls import path
from . import views


app_name = 'teacher'
urlpatterns = [
    path('login/', views.login, name='loginTeacher'),
    path('register/', views.register, name='registerTeacher'),
]

home/models.py
from django.db import models

# Create your models here.

students/models.py
from django.db import models

# Create your models here.

teachers/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.

def start(request):
    return render(request, 'home/start/index.html',)

def registration(request):
    return render(request, 'home/Registration/index.html',)

students/views.py
from django.shortcuts import render

# Create your views here.
def login(request):
    return render(request, 'students/loginStudent.html',)
def register(request):
    return render(request, 'students/registerStudent.html',)

teachers/views.py
from django.shortcuts import render

# Create your views here.


def login(request):
    return render(request, 'teachers/loginTeacher.html',)
def register(request):
    return render(request, 'teachers/registerTeacher.html',)

home/templates/home/start/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- META -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <meta name="author" content="#">
    <meta name="description" content="#">
    <meta name="referrer" content="unsafe-url">
    <meta name="robots" content="index, follow">
    <!-- SPEED -->
    <link rel="preconnect" href="https://res.cloudinary.com">
    <link rel="dns-prefetch" href="https://res.cloudinary.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="dns-prefetch" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <!-- LINK -->
    <link rel="me" href="#">
    <link rel="canonical" href="#">
    <link rel="icon" type="image/png" href="#" sizes="48x48">
    <!-- PERFORMANCE -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap">
    <link rel="preload" as="style" href="{% static 'startstyle.css' %}">
    <link rel="stylesheet"  href="{% static 'startstyle.css' %}">
    <!-- TITLE -->
    <title>The Beginning</title>
  </head>
  <body>
 
  
    <main role="main">
      <section class="ui-section-content">
        <div class="ui-layout-container">
          <!-- COPYWRITING -->
          <div class="ui-layout-column-6 ui-layout-column-center">
            <h1>Attendance App.</h1>

       
            
          </div>
          
          <!-- IMAGE -->
         
        </div>
    
    </main>
    
  </head>
  <body>
      <a href={% url 'home:registration' %} >
        {# <a href="/registration"> #}
          <span>Get Started</span>
          <div class="liquid"></div>
      </a>
    <footer role="contentinfo" class="ui-section-footer">
    
    </footer>
  </body>
</html>

students/templates/students/loginStudent.html
{% extends "teachers/base.html" %}
{% load static %}

{% block style %}
  <link rel="preload" as="style" href="{% static 'studentloginstyle.css' %}">
  <link rel="stylesheet" href="{% static 'studentloginstyle.css' %}">
    
{% endblock style %}
  
  {% block title %}
    <title>student login</title>
    
  {% endblock title %}
    <!-- TITLE -->

    {% block main %}
    <main role="main">
      <section class="ui-section-content">
        <div class="ui-layout-container">
      
          <div class="ui-layout-column-6 ui-layout-column-center">
              <div class="ui-component-cta ui-layout-flex">
            <div class="input-container">
              <input type="email" class="input" placeholder="username">
            </div>
               
      <div class="ui-component-cta ui-layout-flex">
            <div class="input-container">
              <input type="password" class="input" placeholder="password">
            </div>
            
    
   
            
          </div>
       
   
             </div>
          </div>
        </div>
 
    </main>
     <a href="#">
          <span>Login</span>
          <div class="liquid"></div>
         
      </a>
      
{% endblock main %}
    

students/templates/students/registerStudent.html
{% extends "teachers/base.html" %}
{% load static %}

{% block style %}
  <link rel="preload" as="style" href="{% static 'studentloginstyle.css' %}">
  <link rel="stylesheet" href="{% static 'studentloginstyle.css' %}">
    
{% endblock style %}

      <!-- TITLE -->
  {% block title %}
    <title>student registration</title>
    
  {% endblock title %}

{% block main %}
    <main role="main">
      <section class="ui-section-content">
        <div class="ui-layout-container">
      
          <div class="ui-layout-column-6 ui-layout-column-center">
              <div class="ui-component-cta ui-layout-flex">
            <div class="input-container">
              <input type="email" class="input" placeholder="username">
            </div>
                <div class="ui-component-cta ui-layout-flex">
            <div class="input-container">
              <input type="text" class="input" placeholder="Matric Number">
            </div>
            
            </div>
      <div class="ui-component-cta ui-layout-flex">
            <div class="input-container">
              <input type="password" class="input" placeholder="password">
            </div>
            
            </div>
      <div class="ui-component-cta ui-layout-flex">
            <div class="input-container">
              <input type="password" class="input" placeholder="confirm password">
            </div>
            
            </div>
   
            
          </div>
       
   
             </div>
          </div>
        </div>
 
    </main>
     <a href="#">
          <span>Register</span>
          <div class="liquid"></div>
         
      </a>
      
{% endblock main%}

teachers/templates/teachers/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- META -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="author" content="#">
    <meta name="description" content="#">
    <meta name="referrer" content="unsafe-url">
    <meta name="robots" content="index, follow">
    <!-- SPEED -->
    <link rel="preconnect" href="https://res.cloudinary.com">
    <link rel="dns-prefetch" href="https://res.cloudinary.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="dns-prefetch" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <!-- LINK -->
    <link rel="me" href="#">
    <link rel="canonical" href="#">
    <link rel="icon" type="image/png" href="#" sizes="48x48">
    <!-- PERFORMANCE -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap">
     {% block style %} {% endblock style %}

    {% block title %}   {% endblock title %}
  </head>
  
  <body>
     <div class="back">
             <a href="#">
               <p>Back</p>
               </a>
         </div>
    {% block main %} 



    {% endblock main %}
            
  </body>
</html>

teachers/templates/teachers/loginTeacher.html
 {% extends "teachers/base.html" %}
{% load static %}

{% block style %}
 <link rel="preload" as="style" href="{% static 'loginstyle.css' %}">
 <link rel="stylesheet" href="{% static 'loginstyle.css' %}">
{% endblock style %}
 
{% block title %}
  <title>login</title>
{% endblock title %}

 {% block main %}
 
    <main role="main">
      <section class="ui-section-content">
        <div class="ui-layout-container">
      
          <div class="ui-layout-column-6 ui-layout-column-center">
              <div class="ui-component-cta ui-layout-flex">
            <div class="input-container">
              <input type="email" class="input" placeholder="username">
            </div>
               
      <div class="ui-component-cta ui-layout-flex">
            <div class="input-container">
              <input type="password" class="input" placeholder="password">
            </div>
            
    
   
            
          </div>
       
   
             </div>
          </div>
        </div>
 
    </main>
     <a href="#">
          <span>Login</span>
          <div class="liquid"></div>
         
      </a>
   {% endblock main %}
          
      

teachers/templates/teachers/registerTeacher.html
{% load static %}

{% block style %}
  <link rel="preload" as="style"href="{% static 'teacherregisterstyle.css' %}">
  <link rel="stylesheet" href="{% static 'teacherregisterstyle.css' %}">
{% endblock style %}
    <!-- TITLE -->
{% block title %}
      <title>Register</title>
{% endblock title %}
       <div class="back">
      <p>Back</p>
    </div>
    
{% block main %}
  <main role="main">
      <section class="ui-section-content">
        <div class="ui-layout-container">
      
          <div class="ui-layout-column-6 ui-layout-column-center">
              <div class="ui-component-cta ui-layout-flex">
            <div class="input-container">
              <input type="email" class="input" placeholder="username">
            </div>
            <div class="option">
              <select class="option-container" placeholder="data">
                <option value="100LEVEL">Biochemistry</option>
                <option value="100LEVEL">Computer Science</option>
                <option value="100LEVEL">Physics</option>
                <option value="100LEVEL">Industrial Chemistry</option>
                <option value="100LEVEL">Micro Biology</option>
              </select>
            </div>
            <div class="option1">
              <select class="option-container1">
                <option value="100LEVEL">100Level</option>
                <option value="100LEVEL">200Level</option>
                <option value="100LEVEL">300Level</option>
                <option value="100LEVEL">400Level</option>
                <option value="100LEVEL">500Level</option>
              </select>
            </div>






<div class="password">

      <div class="ui-component-cta ui-layout-flex">
            <div class="input-contain">
              <input type="password" class="input" placeholder="password">
            </div>
            
            </div>
      <div class="ui-component-cta ui-layout-flex">
            <div class="input-contain">
              <input type="password" class="input" placeholder="confirm password">
            </div>
            
            </div>
            </div>
   
            
          </div>
       
   
             </div>
          </div>
        </div>
 
    </main>
     <a href="#">
          <span>Login</span>
          <div class="liquid"></div>
         
      </a>
      
          
      <script>
        document.querySelectorAll('.input-container[data-error] .input').forEach(inpEl => {
inpEl.addEventListener('input', () => inpEl.parentElement.removeAttribute('data-error'));
        });
      </script>
{% endblock main %} 
    
</html>